### ISSUE TITLE
AudioPluginHostHelper.parseAapMetadata() needs to become more torelant

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/android-audio-plugin-framework#52]
`AudioPluginHostHelper.parseAapMetadata() ` should not cause a runtime crash when there is a plugin who provides bogus `aap_metadata.xml`. For example, whichever has "nan" on the `default` value of a `<port>` element:

```
2020-07-15 07:04:06.639 4174-4174/org.androidaudioplugin.aaphostsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.androidaudioplugin.aaphostsample, PID: 4174
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.androidaudioplugin.aaphostsample/org.androidaudioplugin.aaphostsample.MainActivity}: java.lang.NumberFormatException: For input string: "nan"
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NumberFormatException: For input string: "nan"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at org.androidaudioplugin.AudioPluginHostHelper$Companion.parseAapMetadata(AudioPluginHostHelper.kt:69)
        at org.androidaudioplugin.AudioPluginHostHelper$Companion.queryAudioPluginServices(AudioPluginHostHelper.kt:111)
        at org.androidaudioplugin.AudioPluginHost.<init>(AudioPluginHost.kt:150)
        at org.androidaudioplugin.aaphostsample.MainActivity.onCreate(MainActivity.kt:119)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by atsushieno** [comment]
It is regarded as fixed by 9b760b0.
